apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ghademo.fullname" . }}
  labels:
{{ include "ghademo.labels" . | indent 4 }}
data:
  {{- range $key, $value := .Values.env.public }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}