{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghademo.fullname" . }}
  labels:
{{ include "ghademo.labels" . | indent 4 }}
data:
{{- range $key, $value := .Values.env.private }}
  {{ $key }}: {{ $value | b64enc }}
{{- end -}}
{{- end -}}

